language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t amilinko/docker-react-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true amilinko/docker-react-ci npm run test -- --coverage